version: '3'
services:
  postgres:
    image: postgres:11.10
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD: i-love-plants
      POSTGRES_USER: greenhouse
      POSTGRES_DB: greenhouse
